### ISSUE TITLE
Peut on avoir aussi les autres paramètres

### ISSUE THREAD

**Issue by histoirede** [Aymkdn/assistant-temperature-local#1]
Bonjour,
c'est très sympa d'avoir la température du quartier, existe t'il une commande pour avoir les autres paramètres, humidité, pression, la hauteur de pluie dans la journée?
Merci.

**Comment by Aymkdn** [comment]
Non y'a pas. Je n'en vois pas trop l'utilité en fait... Mais ça devrait être faisable.
